version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
  docker-springboot-mongodb:
    image: docker-springboot-mongodb:1.0
    container_name: docker-springboot-mongodb
    ports:
      - 8080:8080
    links:
      - mymongodb